{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autoblock.fullname" . }}-secrets
  labels: {{- include "autoblock.labels" . | nindent 4 }}
type: Opaque
stringData:
  AUTOBLOCK_API_AUTH_KEYS_0_KEY: {{ .Values.auth.adminKey | quote }}
  AUTOBLOCK_API_AUTH_KEYS_0_ROLE: "admin"
  {{- if .Values.auth.readonlyKey }}
  AUTOBLOCK_API_AUTH_KEYS_1_KEY: {{ .Values.auth.readonlyKey | quote }}
  AUTOBLOCK_API_AUTH_KEYS_1_ROLE: "readonly"
  {{- end }}
  {{- if .Values.notifications.slack.enabled }}
  AUTOBLOCK_NOTIFICATIONS_SLACK_WEBHOOK_URL: {{ .Values.notifications.slack.webhookUrl | quote }}
  {{- end }}
  {{- if .Values.notifications.pagerduty.enabled }}
  AUTOBLOCK_NOTIFICATIONS_PAGERDUTY_INTEGRATION_KEY: {{ .Values.notifications.pagerduty.integrationKey | quote }}
  {{- end }}
  {{- if .Values.waf.providers.aws.enabled }}
  AWS_ACCESS_KEY_ID: {{ .Values.waf.providers.aws.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.waf.providers.aws.secretAccessKey | quote }}
  {{- end }}
  {{- if .Values.waf.providers.cloudflare.enabled }}
  CF_API_TOKEN: {{ .Values.waf.providers.cloudflare.apiToken | quote }}
  {{- end }}
{{- end }}
